# Generated by Django 5.2.6 on 2025-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Эмоциональная окраска'),
        ),
        migrations.AddField(
            model_name='entry',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность анализа'),
        ),
    ]
