# Generated by Django 5.2.6 on 2025-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_entry_sentiment_label_entry_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mentioned_people',
            field=models.JSONField(blank=True, default=list, verbose_name='Упомянутые люди'),
        ),
    ]
